# Generated by Django 4.0.4 on 2022-05-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40, verbose_name='Страна эмитента')),
                ('tax_rate', models.IntegerField(verbose_name='Налоговая ставка')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
